---
- name: Check web app for DR State
  uri:
    url: "http://{{ ansible_host }}"
    return_content: yes
  register: webpage

- name: Fail if DR is not in the page content
  fail:
  when: "'DR' not in webpage.content"
